apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
        track: stable
    spec:
      containers:
        - image: url-up-pushed-image
          imagePullPolicy: Always
          name: registry
          ports:
          - containerPort: 500
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /images
          volumeMounts:
             - name: docker-stateful
               mountPath: /images
      volumes:
         - name: docker-stateful
           persistentVolumeClaim:
             claimName: docker-stateful-claim-1
